services:
  - type: web
    name: telegram-copy-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: TELEGRAM_SESSION_STRING
        sync: false
      - key: TARGET_CHANNEL
        value: yukspriter
      - key: SOURCE_CHANNELS
        value: yuk_markazi_bogdod,Gmail058omad,yuk_markazi_gruppaaaa,Yuk_markazi_kia_hunday_isuzu_yuk,kia_hunday_yuk